const fs = require("fs");
const path = require("path");

// Get all the .vue files in the src directory
const componentNames = fs
  .readdirSync(path.resolve(__dirname, "../src"))
  .filter(componentFileName => /\.vue$/.test(componentFileName))
  .map(componentFileName => componentFileName.replace(/\.\w+$/, ""));

const indexFileContent = `\
// THIS FILE IS AUTOMATICALLY GENERATED
${componentNames
  .map(componentName => `import ${componentName} from './${componentName}.vue'`)
  .join("\n")}

// Export components individually
export { ${componentNames.map(componentName => componentName).join(", ")} }

// What should happen if the user installs the library as a plugin
function install(Vue) {
${componentNames
  .map(componentName => `  Vue.component('${componentName}', ${componentName})`)
  .join("\n")}
}

// Export the library as a plugin
export default { install: install }
`;

fs.writeFileSync(path.resolve(__dirname, "../src/index.js"), indexFileContent);
