// THIS FILE IS AUTOMATICALLY GENERATED
import AppBar from './AppBar/AppBar.vue'
import AppCss from './AppCss/AppCss.vue'
import Autocomplete from './Autocomplete/Autocomplete.vue'
import Badge from './Badge/Badge.vue'
import Button from './Button/Button.vue'
import ButtonIcon from './ButtonIcon/ButtonIcon.vue'
import Buttons from './Buttons/Buttons.vue'
import Card from './Card/Card.vue'
import Container from './Container/Container.vue'
import Icon from './Icon/Icon.vue'
import Img from './Img/Img.vue'
import ImgProvider from './ImgProvider/ImgProvider.vue'
import Input from './Input/Input.vue'
import Tag from './Tag/Tag.vue'
import Theme from './Theme/Theme.vue'
import H1 from './Typography/H1.vue'
import H2 from './Typography/H2.vue'
import H3 from './Typography/H3.vue'
import H4 from './Typography/H4.vue'
import H5 from './Typography/H5.vue'
import H6 from './Typography/H6.vue'
import Label from './Typography/Label.vue'
import Overline from './Typography/Overline.vue'
import P from './Typography/P.vue'
import P2 from './Typography/P2.vue'
import Txt from './Typography/Txt.vue'
import Txt2 from './Typography/Txt2.vue'
import * as color from './util/color.js'
import * as icon from './util/icon.js'
import * as propValidators from './util/propValidators.js'
import * as props from './util/props.js'
import * as shadow from './util/shadow.js'
import * as spacing from './util/spacing.js'
import * as theme from './util/theme.js'
import * as typography from './util/typography.js'

// Install components globally
const install = Vue => {
  Vue.component('AppBar', AppBar)
  Vue.component('AppCss', AppCss)
  Vue.component('Autocomplete', Autocomplete)
  Vue.component('Badge', Badge)
  Vue.component('Button', Button)
  Vue.component('ButtonIcon', ButtonIcon)
  Vue.component('Buttons', Buttons)
  Vue.component('Card', Card)
  Vue.component('Container', Container)
  Vue.component('Icon', Icon)
  Vue.component('Img', Img)
  Vue.component('ImgProvider', ImgProvider)
  Vue.component('Input', Input)
  Vue.component('Tag', Tag)
  Vue.component('Theme', Theme)
  Vue.component('H1', H1)
  Vue.component('H2', H2)
  Vue.component('H3', H3)
  Vue.component('H4', H4)
  Vue.component('H5', H5)
  Vue.component('H6', H6)
  Vue.component('Label', Label)
  Vue.component('Overline', Overline)
  Vue.component('P', P)
  Vue.component('P2', P2)
  Vue.component('Txt', Txt)
  Vue.component('Txt2', Txt2)
}

// Export library as a plugin, and individual components
export default { install }
export {
  AppBar,
  AppCss,
  Autocomplete,
  Badge,
  Button,
  ButtonIcon,
  Buttons,
  Card,
  Container,
  Icon,
  Img,
  ImgProvider,
  Input,
  Tag,
  Theme,
  H1,
  H2,
  H3,
  H4,
  H5,
  H6,
  Label,
  Overline,
  P,
  P2,
  Txt,
  Txt2,
  color,
  icon,
  propValidators,
  props,
  shadow,
  spacing,
  theme,
  typography,
}
