// THIS FILE IS AUTOMATICALLY GENERATED
import App from './App.vue'
import AppInput from './AppInput.vue'
import Bar from './Bar.vue'
import HelloWorld from './HelloWorld.vue'

// Export components individually
export { App, AppInput, Bar, HelloWorld }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('App', App)
  Vue.component('AppInput', AppInput)
  Vue.component('Bar', Bar)
  Vue.component('HelloWorld', HelloWorld)
}

// Export the library as a plugin
export default { install: install }
