// THIS FILE IS AUTOMATICALLY GENERATED
import AppCss from './AppCss/AppCss.vue'
import Autocomplete from './Autocomplete/Autocomplete.vue'
import Bar from './Bar/Bar.vue'
import Button from './Button/Button.vue'
import Input from './Input/Input.vue'
import Theme from './Theme/Theme.vue'

// Install components globally
const install = Vue => {
  Vue.component('AppCss', AppCss)
  Vue.component('Autocomplete', Autocomplete)
  Vue.component('Bar', Bar)
  Vue.component('Button', Button)
  Vue.component('Input', Input)
  Vue.component('Theme', Theme)
}

// Export library as a plugin, and individual components
export default { install }
export { AppCss, Autocomplete, Bar, Button, Input, Theme }
